%***********************************************************************
% Discription:  Update UAV search position according to action sequence
% input:        uav                 UAV structure
% input:        individual          Current action sequence 
% output:       uav                 UAV structure
%***********************************************************************

function uav=Update_Search_CMD(uav,individual)
%% Generate state sequence and yaw sequence according to action sequence 
[position_series,yaw_series,~]=...                   
    Generate_Route(uav,individual);

%% Set fist state in state sequence as next time search position 
uav.xr=uav.map_x_min+...
    position_series(uav.search_index,1)*...
    uav.map_grid_size-...
    0.5*uav.map_grid_size;
uav.yr=uav.map_y_min+...
    position_series(uav.search_index,2)*...
    uav.map_grid_size-...
    0.5*uav.map_grid_size;
uav.yaw_r=yaw_series(uav.search_index);

%% Record the pre planned search position of the UAV
for i=1:uav.foresee_num
    uav.perdict_pos_self(i,1)=uav.map_x_min+...
    position_series(i,1)*...
    uav.map_grid_size-...
    0.5*uav.map_grid_size;
    uav.perdict_pos_self(i,2)=uav.map_y_min+...
    position_series(i,2)*...
    uav.map_grid_size-...
    0.5*uav.map_grid_size;
end
end

