%*****************************************************************************
% Discription:  Create UAVs structure array of controller
% input:        property_uav        UAVs property structure
% input:        UAV_Coordinate      UAVs structure array in companion computer
% input:        map                 Map structure
% output:       UAV                 UAVs structure array in controller
%*****************************************************************************

function UAV = Creat_UAV_Control(property_uav,UAV_Coordinate,map)
uav_stru=struct(...
    'x',0,'y',0,...
    'xg',0,'yg',0,...
    'xr',0,'yr',0,...
    'vel',0,'vx',0,'vy',0,...
    'acc',0,'ax',0,'ay',0,...
    'yaw',0,'yaw_r',0,...
    'map_x_min',map.x_min,...
    'map_x_max',map.x_max,...
    'map_y_min',map.y_min,...
    'map_y_max',map.y_max,...
    'map_grid_size',map.grid_size,...
    'PID_roll',[0,0,0],...
    'PID_pitch',[0,0,0],...
    'PID_yaw',[0,0,0]);
UAV(1:property_uav.num)=uav_stru;

for i=1:property_uav.num
    UAV(i).x=UAV_Coordinate(i).x;
    UAV(i).y=UAV_Coordinate(i).y;
    UAV(i).xg=UAV_Coordinate(i).xg;
    UAV(i).yg=UAV_Coordinate(i).yg;
end
end